Move optional dependencies
lincc-frameworks/superphot-plus pull request #141
Opened 2023-09-07 19:59 UTC by delucchi-cmu

## Change Description

Moves several dependencies into feature subsets, and includes all subsets for CI.

## Code Quality
- [x] I have read the Contribution Guide
- [x] My code follows the code style of this project
- [ ] My code builds (or compiles) cleanly without any errors or warnings
- [x] My code contains relevant comments and necessary documentation

2023-09-08 13:54 UTC, kdesoto-astro requested changes

2023-09-08 13:54 UTC, kdesoto-astro commented on pyproject.toml
> +runtime-ml = [
can we change this to something that makes it clear these are for the Samplers/fitting step? runtime-ml may confuse users into thinking this is for classifier training

2023-09-08 13:59 UTC, camposandro commented on pyproject.toml
> +    "ray",
We can remove this one because of the `ray[tune]` dependency below

2023-09-08 14:28 UTC, camposandro approved these changes

2023-09-09 01:30 UTC, kdesoto-astro approved these changes

2023-09-09 01:32 UTC, merged