Update make_fake_spp_data.py
lincc-frameworks/superphot-plus pull request #37
Opened 2023-07-20 20:10 UTC by villrv

Updated injection to produce somewhat realistic ZTF-like light curves and keep track of parameters

## Change Description

## Code Quality
- [ ] I have read the Contribution Guide
- [ ] My code follows the code style of this project
- [ ] My code builds (or compiles) cleanly without any errors or warnings
- [ ] My code contains relevant comments and necessary documentation

2023-07-20 20:10 UTC, villrv commented
I would just like to add here that I am so sorry for how bad I am at github, Melissa!!!

2023-07-21 18:53 UTC, jeremykubica requested changes

2023-07-21 18:53 UTC, jeremykubica commented on src/superphot_plus/data_generation/make_fake_spp_data.py
> -def create_clean_models(nmodels, num_times=100):
Removing this function will break the unit tests in tests/superphot_plus/data_generation/test_make_fake_spp_data.py. One solution is to remove those tests. However, I actually think it is useful to have a function that generates clean models to use in testing. Is that possible to do with the new function (using the snr ranges)?

2023-07-21 19:01 UTC, jeremykubica commented on src/superphot_plus/data_generation/make_fake_spp_data.py
> +    gind = np.where(snr>3)
What does `gind` represent? Are these good indices?

2023-07-24 17:23 UTC, kdesoto-psu commented
Implemented requested changes

2023-07-24 17:45 UTC, jeremykubica reviewed
Looks good. I added a bunch of comments. The main request is that we make the doc strings consistent with the rest of the code.

Adding a unit test would be great, but isn't blocking.

It might also be worth running black formatting on the code (just `black .` from the command line in the top level directory)

2023-07-24 17:45 UTC, jeremykubica commented on src/superphot_plus/data_generation/make_fake_spp_data.py
> +    inputs:
Small formatting request: For consistency we use the same formatting we have been using in other doc strings?

```
    Parameters
    ----------
    parameter_name : type
        Description
```

2023-07-24 17:45 UTC, jeremykubica commented on src/superphot_plus/data_generation/make_fake_spp_data.py
> +    snr[gind_r] = (snr_range_r[1] - snr_range_r[0]) * (mag[gind_r] - np.min(mag[gind_r])) / range_r + snr_range_r[0]
Since this function is deterministic, would it be possible to add a unit test?

2023-07-24 17:45 UTC, jeremykubica commented on src/superphot_plus/data_generation/make_fake_spp_data.py
> -def create_clean_models(nmodels, num_times=100):
Thank you!

2023-07-24 17:45 UTC, jeremykubica commented on src/superphot_plus/data_generation/make_fake_spp_data.py
> +    inputs:
Same formatting request as above: For consistency we use the same formatting we have been using in other doc strings?

2023-07-24 17:45 UTC, jeremykubica commented on src/superphot_plus/data_generation/make_fake_spp_data.py
> +    # This is going to random simulate some observation every 2-3 days across 2 filters
Good comment. It pre-answers my questions about the details.

2023-07-24 17:45 UTC, jeremykubica commented on src/superphot_plus/data_generation/make_fake_spp_data.py
> +    filter_data = np.random.choice(['g','r'],size=num_observations)
Small formatting: There should be a space after the comma.

2023-07-24 17:45 UTC, jeremykubica commented on src/superphot_plus/data_generation/make_fake_spp_data.py
> +    dirty_model = f_model + np.random.normal(0,sigmas)
Small formatting: There should be a space after the comma.

2023-07-25 00:01 UTC, jeremykubica approved these changes
Nice set of changes. Good call in bringing in `constants` and `params_valid`.

Only one small comment, but otherwise you are good to merge.

2023-07-25 00:14 UTC, merged